os: linux
dist: focal
language: cpp

sudo: required

compiler:
  - clang
  - gcc

stages:
  - compile
  - test

before_install:
  - sudo apt-get update -qq

install:

  - sudo apt-get install -qq qt5-default
  - sudo apt-get install -qq cmake make
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq libgtest-dev
  - sudo apt-get install -qq qtdeclarative5-dev
  - sudo apt-get install -qq qtbase5-dev
  - sudo apt-get install -qq clang


jobs:
  include:
    - stage: compile
      name: "Compile stage"
      script:
      - ./compile.sh
    # run tests using the binary built before
    - stage: test
      name: "Test stage"
      script:
      - ./build/test

