os: linux
dist: focal
language: cpp

stages:
  - mainTest

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default
  - sudo apt-get install -qq cmake make
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq libgtest-dev
  - sudo apt-get install -qq qtdeclarative5-dev
  - sudo apt-get install -qq qtbase5-dev
  - sudo apt-get install -qq clang

jobs:
  include:
    - stage: mainTest
      name: "gcc and clang test stage"
      script:
        - ./compile.sh g++ gcc
        - ./build/test
        - ./compile.sh clang++ clang
        - ./build/test




