os: linux
language: cpp

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default
  - sudo apt-get install -qq cmake make
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq libgtest-dev
  - sudo apt-get install -qq qtdeclarative5-dev
  - sudo apt-get install -qq qtbase5-dev

sudo: required
jobs:
  include:
    - stage: "Build"
      script: ./build.sh
    # run tests using the binary built before
    - stage: "test"
      script: ./build/test

