os: linux
language: cpp

sudo: required

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default
  - sudo apt-get install -qq cmake make

compiler:
  - clang
  - gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf

  script:
    - rm -r build
    - mkdir build
    - cd build
    - cmake ..
    - make
# run tests using the binary built before
test:
  stage: test
  script:
    - ./build/test
