os: linux
dist: focal
language: cpp

stages:
  - gccTest
  - clangTest

before_install:
  - sudo apt-get update -qq

install:

  - sudo apt-get install -qq qt5-default
  - sudo apt-get install -qq cmake make
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq libgtest-dev
  - sudo apt-get install -qq qtdeclarative5-dev
  - sudo apt-get install -qq qtbase5-dev


jobs:
  include:
    - stage: gccTest
      name: "gcc test stage"
      compiler:
        - gcc

    - stage: clangTest
      name: "clang test stage"
      env:
        - MATRIX_EVAL="CC=clang-10.0 && CXX=clang++-10.0"
      install:
        - sudo apt-get install -qq clang
      compiler:
        - clang

script:
  - ./compile.sh
  - ./build/test

