os: linux
dist: focal
language: cpp

stages:
  - mainTest

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default
  - sudo apt-get install -qq cmake make
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq libgtest-dev
  - sudo apt-get install -qq qtdeclarative5-dev
  - sudo apt-get install -qq qtbase5-dev
  - sudo apt-get install -qq clang gcc
  - sudo apt-get install -qq gcovr lcov

jobs:
  include:
    - stage: mainTest
      name: "gcc and clang test stage"
      script:
        - ./compile.sh --compiler clang clang++ --debug --cmake -t calculator -t test
        - ./build/test
        - ./compile.sh --compiler gcc g++ --debug --coverage --cmake -t calculator -t test
        - ./build/test

        - ./compile.sh --compiler gcc g++ --debug --coverage --cmake -t test
        - ./build/test

        - lcov --version
        - lcov --directory . --capture --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' --output-file coverage.info
        - lcov --list coverage.info
        - bash <(curl -s https://codecov.io/bash)


