os: linux
language: cpp

sudo: required

compiler:
  - clang
  - gcc

stages:
  - build
  - test

before_install:
  - sudo apt-get update -qq

install:

  - sudo apt-get install -qq qt5-default
  - sudo apt-get install -qq cmake make
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq libgtest-dev
  - sudo apt-get install -qq qtdeclarative5-dev
  - sudo apt-get install -qq qtbase5-dev


jobs:
  include:
    - stage: build
      name: "Build stage"
      script:
      - ./build.sh
    # run tests using the binary built before
    - stage: test
      name: "Test stage"
      script:
      - ./build/test

